// GENERATED by scripts/extract-questionnaire.mjs from source/src/lib/questionnaireData.ts and the old questionnaire
// screens. Do not edit by hand; re-run the script. Wording, options and order are the old site's, unchanged.

export interface SubOption {
  /** stable id for this option */
  id: string;
  /** label shown to the user */
  label: string;
  /** if true, shows a free-text "Something Else" box when selected */
  hasOtherBox?: boolean;
  /** if true, reveals the "Which software do you need help with?" submenu */
  triggersSoftware?: boolean;
}

export interface SubSection {
  /** optional sub-heading (SMSF & Financial Planning has two) */
  heading?: string;
  options: SubOption[];
}

export interface MatchCategory {
  id: string;
  label: string;
  /** small subtitle shown under the label (New Business & Registrations) */
  subtitle?: string;
  sections: SubSection[];
}

// The four top-level options shown in the "Let's find your match" card.
export const MATCH_CATEGORIES: MatchCategory[] = [
  {
    id: "personal_tax",
    label: "Personal Tax Returns and Planning",
    sections: [
      {
        options: [
          { id: "lodge", label: "Lodge My Tax Return" },
          { id: "late", label: "Late or Overdue Tax Returns" },
          { id: "property", label: "Investment Property Rental Income" },
          { id: "shares", label: "Shares, Crypto or Capital Gains" },
          { id: "sole", label: "Sole Trader / Self-Employed Income" },
          { id: "planning", label: "Tax Planning and Deductions" },
          { id: "ato_audit", label: "ATO Audit Assistance" },
          { id: "other", label: "Something Else", hasOtherBox: true },
        ],
      },
    ],
  },
  {
    id: "business",
    label: "Business Services",
    subtitle: "(Sole Trader, Company, Partnership)",
    sections: [
      {
        options: [
          { id: "biz_returns", label: "Business tax returns" },
          { id: "bookkeeping", label: "Bookkeeping, BAS, GST, and PAYG" },
          { id: "payroll", label: "Payroll and employee super" },
          { id: "financials", label: "Financial statements and reports" },
          { id: "biz_planning", label: "Tax planning and business structure" },
          {
            id: "cashflow",
            label: "Cash flow, budgeting, and business advice",
          },
          { id: "overdue", label: "Overdue tax returns, BAS, or bookkeeping" },
          { id: "ato_audit", label: "ATO Audit Assistance" },
          {
            id: "software",
            label: "Xero, MYOB, or QuickBooks help",
            triggersSoftware: true,
          },
          { id: "new_biz", label: "New business and registrations" },
        ],
      },
    ],
  },
  {
    id: "smsf_fp",
    label: "SMSF and Financial Planning",
    sections: [
      {
        heading: "SMSF Services",
        options: [
          { id: "smsf_setup", label: "Setting up an SMSF" },
          {
            id: "smsf_acct",
            label: "SMSF accounting, tax returns, and administration",
          },
          { id: "smsf_audit", label: "SMSF audit" },
          { id: "smsf_borrow", label: "SMSF borrowing and property purchases" },
          { id: "smsf_pension", label: "SMSF pensions and retirement" },
          { id: "smsf_close", label: "Closing an SMSF" },
          { id: "ato_audit", label: "ATO Audit Assistance" },
          { id: "smsf_other", label: "Something else", hasOtherBox: true },
        ],
      },
      {
        heading: "Financial Planning",
        options: [
          { id: "fp_super", label: "Superannuation advice" },
          { id: "fp_retire", label: "Retirement planning" },
          { id: "fp_invest", label: "Investment advice" },
          { id: "fp_insurance", label: "Personal insurance advice" },
          { id: "fp_plan", label: "Comprehensive financial plan" },
          { id: "fp_other", label: "Something else", hasOtherBox: true },
        ],
      },
    ],
  },
  {
    id: "new_business",
    label: "Registration Services",
    subtitle: "(New Company, Business Name, ABN, GST, TFN).",
    sections: [
      {
        options: [
          { id: "structure", label: "Start business / Choosing structure" },
          { id: "ptyltd", label: "Setting up a Pty Ltd (ASIC registration)" },
          { id: "abn", label: "Applying for an ABN" },
          { id: "biz_name", label: "Registering a business name" },
          { id: "gst", label: "Registering for GST" },
          {
            id: "payg",
            label: "Registering as an employer (PAYG withholding)",
          },
          { id: "trust", label: "Setting up a trust or partnership" },
          { id: "other", label: "Something else", hasOtherBox: true },
        ],
      },
    ],
  },
];

export const SOFTWARE_OPTIONS = [
  "Xero",
  "MYOB",
  "QuickBooks",
  "Other software",
];

/** First-page wording of the old questionnaire (verified against /source by the extractor). */
export const QUESTIONNAIRE_UI = {
  "progressBadge": "Your Match in Progress",
  "introHeading": "We ask a couple more questions than most.",
  "introText": "That’s how we match you perfectly the first time — so you don’t waste your time starting over with someone who isn’t quite right.",
  "stepOf": "Step {n} of {total}",
  "categoryOf": "Category {n} of {total}",
  "smsfHelpBefore": "Choose just",
  "smsfHelpStrong": "one option",
  "smsfHelpAfter": "from either section below — that's all we need to match you with the right specialist.",
  "defaultHelp": "Select all that apply — we’ll use these to match you with an accountant in your area who specialises in {category}.",
  "otherBoxLabel": "Please let us know a little more detail",
  "otherBoxPlaceholder": "Tell us what you need help with…",
  "softwareHeading": "Which software do you need help with?",
  "softwareError": "Please select a software package to continue",
  "softwareErrorFull": "Please select a software package to continue.",
  "smsfError": "Please select at least one option from either section to continue.",
  "defaultError": "Please select at least one option to continue.",
  "back": "Back",
  "next": "Next"
} as const;
