// Compares the WORDS on the new sample pages with the words on the old pages.
//   node scripts/compare-words.mjs <port>
// For each sample page it opens the new page in a browser and checks, both ways:
//   MISSING — old words (phone or desktop version of the old page) that are not on the new page
//   ADDED   — words on the new page that were not on the old page
// Writes docs/word-check-stage2.md.
import { chromium } from "playwright";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const port = process.argv[2] || "3217";
const SAMPLES = [
  "/", "/locations", "/locations/sydney", "/industry/real-estate-property/sydney", "/accountant/tax-accountant",
  "/guides", "/guide/accountant-near-me", "/blog", "/blog/bas-due-dates-2026", "/about", "/contact", "/how-it-works",
  "/how-we-select-accountants", "/privacy", "/terms",
];
// Pages whose wording was deliberately replaced by the site owner (see docs/plan.md)
const APPROVED_REPLACEMENT = new Set(["/how-we-select-accountants"]);

const norm = (s) => s.toLowerCase().replace(/[’‘]/g, "'").replace(/[^a-z0-9']+/g, " ").replace(/'/g, "").trim();
const slugOf = (p) => (p === "/" ? "_home" : p.replace(/^\/|\/$/g, "").replace(/[\/?=&]/g, "__"));

// Old picture descriptions are not page words, except these three graphics whose words the new page shows as real text.
const GRAPHIC_ALT = /^(Our 3 Step Matching Process|The Difference|Matching accountants to every kind of client|Step \d)/;
const altItems = (alt) => alt.replace(/^[^:—]*[:—]\s*/, "").split(/,\s*|\d\.\s+/).map((x) => x.trim()).filter(Boolean);

const unitsOf = (nodes, out) => {
  for (const n of nodes) {
    if (n.t === "list") n.items.forEach((i) => out.push(i.text));
    else if (n.t === "faq") out.push(n.q, n.aText);
    else if (n.t === "img") { if (n.alt && GRAPHIC_ALT.test(n.alt)) out.push(...altItems(n.alt)); }
    else if ("text" in n && typeof n.text === "string") out.push(n.text);
  }
};
const oldUnits = (d) => {
  const out = [];
  unitsOf(d.mobile, out);
  unitsOf(d.nodes, out);
  out.push(...(d.fixed || []));
  return [...new Set(out)].filter((t) => norm(t).length > 0);
};
// Words that exist only in the desktop version of the old page (not used: the new page follows the phone wording)
const desktopOnly = (d) => {
  const m = []; unitsOf(d.mobile, m);
  const mn = norm(m.join(" | "));
  const dd = []; unitsOf(d.nodes, dd);
  return new Set(dd.filter((t) => norm(t).length >= 8 && !mn.includes(norm(t))));
};

const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1280, height: 900 }, reducedMotion: "reduce" });
const page = await ctx.newPage();
let md = "# Word check — Stage 2 sample pages\n\n_Generated by `node scripts/compare-words.mjs`. Compares every sample page's words with the old page (both its phone and desktop versions)._\n\n";
md += "**How to read this:** most remaining \"missing\" and \"added\" lines are measuring artefacts. A card title and its description, a breadcrumb (\"Home / Locations\") or the footer address are on the page but sit in separate elements, so the checker sees them joined without spaces. The real differences are: the old site's search button (not built until Stage 3), desktop-only wording (the new page uses the phone wording; see mobile-desktop-differences.md), and reused wording in new design elements (navigation labels, the call-to-action band, \"Skip to main content\"; see docs/plan.md).\n\n";
const summary = [];
let detail = "";

for (const p of SAMPLES) {
  const file = path.join(ROOT, "data", "structured", slugOf(p) + ".json");
  if (!fs.existsSync(file)) { summary.push(`| ${p} | (no extracted data) | | |`); continue; }
  const d = JSON.parse(fs.readFileSync(file, "utf8"));
  const old = oldUnits(d);
  const dOnly = desktopOnly(d);
  await page.goto(`http://localhost:${port}${p}`, { waitUntil: "networkidle", timeout: 90000 });
  const { all, units, title, alts } = await page.evaluate(() => {
    const clean = (s) => s.replace(/\s+/g, " ").trim();
    const root = document.body;
    const BLOCK = "h1,h2,h3,h4,h5,h6,p,li,summary,dd,dt,td,th,figcaption";
    const units = [];
    // 1) whole text of every block-level element that holds no other block-level element
    for (const e of root.querySelectorAll(BLOCK)) {
      if (e.querySelector(BLOCK)) continue;
      const t = clean(e.textContent || "");
      if (t) units.push(t);
    }
    // 2) loose text that is not inside any of those (buttons, links, spans, divs)
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
    const loose = new Map();
    for (let n = walker.nextNode(); n; n = walker.nextNode()) {
      const t = clean(n.textContent || "");
      if (!t || n.parentElement.closest(BLOCK) || n.parentElement.closest("script,style,noscript")) continue;
      const key = n.parentElement.closest("a,button,label") || n.parentElement;
      loose.set(key, (loose.get(key) ? loose.get(key) + " " : "") + t);
    }
    units.push(...loose.values());
    return { all: clean(root.textContent || ""), units, title: document.title, alts: [...root.querySelectorAll("img")].map((i) => i.alt).filter(Boolean) };
  });
  const allN = norm(units.join(" ") + " " + alts.join(" "));
  const oldN = norm(old.join(" | "));

  const missingAll = old.filter((t) => norm(t).length >= 8 && !allN.includes(norm(t)));
  const missing = missingAll.filter((t) => !dOnly.has(t));
  const missingDesktop = missingAll.filter((t) => dOnly.has(t));
  const added = [...new Set(units)].filter((t) => norm(t).length >= 3 && !oldN.includes(norm(t)) && !alts.includes(t));
  const oldNorm = old.map(norm);

  const approved = APPROVED_REPLACEMENT.has(p);
  summary.push(`| ${p} | ${approved ? "approved new wording" : missing.length + (missingDesktop.length ? " (+" + missingDesktop.length + " desktop-only)" : "")} | ${approved ? "approved new wording" : added.length} | ${old.length} |`);
  detail += `\n## ${p}\n\n`;
  if (approved) { detail += "Wording replaced on purpose with the site owner's approved text (see docs/plan.md); not compared.\n"; continue; }
  detail += `**Missing from the new page (${missing.length}):**\n\n${missing.length ? missing.map((t) => `- ${t.slice(0, 220)}`).join("\n") : "_none_"}\n\n`;
  const NL = String.fromCharCode(10);
  const list = (arr) => (arr.length ? arr.map((t) => "- " + t.slice(0, 220)).join(NL) : "_none_");
  detail += "**Desktop-only old wording not used (new page follows the phone wording) (" + missingDesktop.length + "):**" + NL + NL + list(missingDesktop) + NL + NL;
  detail += `**Added on the new page (${added.length}):**\n\n${added.length ? added.map((t) => `- ${t.slice(0, 220)}`).join("\n") : "_none_"}\n`;
}
md += "| Page | Old words missing | New words added | Old text units checked |\n|---|---:|---:|---:|\n" + summary.join("\n") + "\n" + detail;
fs.writeFileSync(path.join(ROOT, "docs", "word-check-stage2.md"), md);
console.log(summary.join("\n"));
await browser.close();
